# -*- mode: ruby -*-
# vi: set ft=ruby :

# unless Vagrant.has_plugin?("vagrant-docker-login")
#   system("vagrant plugin install vagrant-docker-login")
#   puts "Dependencies installed, please try the command again."
#   exit
# end

unless ENV["DOCKER_USERNAME"] && ENV["DOCKER_PASSWORD"]
  puts "Set your DOCKER_USERNAME and DOCKER_PASSWORD environment variable."
  exit
end

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :docker
  config.vm.provision :docker_login
end
